ccminer mac
tpruvot/ccminer pull request #15
Opened 2017-05-06 08:18 UTC by kangcliff

2017-05-06 08:30 UTC, tpruvot requested changes

2017-05-06 08:30 UTC, tpruvot commented on Makefile.am
> +ccminer_CPPFLAGS += -I/usr/local/opt/openssl/include -I/usr/local/llvm/lib/clang/4.0.0/include
there is no pkgconfig on mac ?

2017-05-06 08:30 UTC, tpruvot commented on scrypt.cpp
> +#if !((defined(__FreeBSD__) && __FreeBSD__ >= 10) || defined(__APPLE__))
im not fan of these reversed if else

2017-05-06 08:30 UTC, tpruvot commented on scrypt/salsa_kernel.h
> +#if !((defined(__FreeBSD__) && __FreeBSD__ >= 10) || defined(__APPLE__))
same

2017-05-06 08:30 UTC, tpruvot commented on configure.ac
> +  LIBCURL_CPPFLAGS=-I/usr/local/opt/curl/include
its supposed to use libcurl.pc in pkgconfig folder for the path (which doesnt look normal here)

2017-05-06 11:01 UTC, kangcliff commented on Makefile.am
> +ccminer_CPPFLAGS += -I/usr/local/opt/openssl/include -I/usr/local/llvm/lib/clang/4.0.0/include
Yeah, but the llvm package I installed doesn't come with .pc files.

2017-05-06 11:10 UTC, kangcliff commented on scrypt.cpp
> +#if !((defined(__FreeBSD__) && __FreeBSD__ >= 10) || defined(__APPLE__))
changed to #ifdef __APPLE__

2017-05-07 14:51 UTC, kangcliff commented
Attached benchmark results on GTX 1070 on stock settings. 

Nvidia Web Driver 378.05.05 with CUDA 8.0.61:
[ccminer_bench_mac.txt](https://github.com/tpruvot/ccminer/files/981648/ccminer_bench.txt)

Geforce Game Ready Driver 382.05 with CUDA 7.5:
[ccminer_bench_win.txt](https://github.com/tpruvot/ccminer/files/981654/ccminer_bench.txt)

2017-05-09 02:32 UTC, tpruvot commented on INSTALL
> +brew install autoconf automake curl openssl llvm
could you try if "brew install pkg-config" works ?

2017-05-09 03:04 UTC, kangcliff commented on INSTALL
> +brew install autoconf automake curl openssl llvm
I installed pkg-config with brew already, but I got nothing from these two lines:

$(shell pkg-config --cflags libcurl)
$(shell pkg-config --cflags libcrypto)

2017-05-09 03:52 UTC, tpruvot commented
I made a commit which "merge" a part of these changes : https://github.com/tpruvot/ccminer/commit/fad5b0470a559b170f30433c4b730c7c53c6c216

2017-05-16 10:27 UTC, nikbass commented
hi. news for this project? 
I'm trying to compile it from a couple of days on my mac pro but without success. Unfortunately, I have no experience
thx advance.

2017-05-18 17:41 UTC, closed without merging

2018-01-15 17:29 UTC, tmikaeld commented
I'm trying to compile this on High Sierra, but setting the compiler flags doesn't help configure to find the curl sources - it does find openssl though.

My FLAGS in build.sh

```bash
CPPFLAGS="-I/usr/local/opt/openssl/include -I/usr/local/opt/curl/include" \
LDFLAGS="-L/usr/local/opt/openssl/lib -L/usr/local/opt/curl/lib" \
./configure.sh
```

The configure error:

```bash
checking for pthread_create in -lpthread... yes
checking for gzopen in -lz... yes
checking for SSL_free in -lssl... yes
checking for EVP_DigestFinal_ex in -lcrypto... yes
./configure: line 6165: syntax error near unexpected token `,'
./configure: line 6165: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,

2018-02-10 20:44 UTC, rooi commented
@tmikaeld have you tried running the following?

`brew link curl --force`

I've written down my actions to build and use tpruvot's ccminer on: https://github.com/rooi/ccminer_macos/README.md